# Macro to add sources to the list of sources
macro (add_sources)
    file (RELATIVE_PATH _relPath "${PROJECT_SOURCE_DIR}" "${CMAKE_CURRENT_SOURCE_DIR}")
    foreach (_src ${ARGN})
        if (_relPath)
            list(APPEND SRCS "${_relPath}/${_src}")
        else()
            list(APPEND SRCS "${_src}")
        endif()
    endforeach()
    if (_relPath)
        # propagate SRCS to parent directory
        set(SRCS ${SRCS} PARENT_SCOPE)
    endif()
endmacro()
