set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(CMAKE_C_COMPILER arm-none-eabi-gcc)
set(CMAKE_C_COMPILER_ID GNU)
set(CMAKE_C_COMPILER_FORCED TRUE)
set(CMAKE_ASM_FLAGS "${CFLAGS} -x assembler-with-cpp -D__ASSEMBLY__")

set(CPU_OPTIONS -mthumb -mcpu=cortex-m4)

add_compile_options(${CPU_OPTIONS})
add_compile_options(-MD)
add_compile_options(-Wdeclaration-after-statement)
add_compile_options(-Wduplicated-branches)
add_compile_options(-Wduplicated-cond)
add_compile_options(-Wempty-body)
add_compile_options(-Werror)
add_compile_options(-Werror-implicit-function-declaration)
add_compile_options(-Wextra)
add_compile_options(-Wignored-qualifiers)
add_compile_options(-Wimplicit-fallthrough)
add_compile_options(-Wmisleading-indentation)
add_compile_options(-Wno-conversion)
add_compile_options(-Wno-sign-compare)
add_compile_options(-Wno-sign-conversion)
add_compile_options(-Wstrict-prototypes)
add_compile_options(-Wuninitialized)
add_compile_options(-Wunknown-pragmas)
add_compile_options(-Wunused-but-set-variable)
add_compile_options(-Wunused-function)
add_compile_options(-Wunused-label)
add_compile_options(-Wunused-result)
add_compile_options(-Wunused-value)
add_compile_options(-Wunused-variable)
add_compile_options(-fno-delete-null-pointer-checks)
add_compile_options(-fno-strict-overflow)

add_link_options(-Wl,-Map=m4naos.map -specs=nano.specs)
